<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK9UQFsk\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK9UQFsk/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerK9UQFsk.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerK9UQFsk\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerK9UQFsk\appAppKernelProdContainer([
    'container.build_hash' => 'K9UQFsk',
    'container.build_id' => '4c2fcee9',
    'container.build_time' => 1710243385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK9UQFsk');
